"""Add cascade delete on user-user_details relationship

Revision ID: 0618a3eea808
Revises: e83671c1d347
Create Date: 2025-04-07 10:07:54.950476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0618a3eea808'
down_revision = 'e83671c1d347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_constraint('user_details_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_details_ibfk_1', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
